export const FETCH_EQUIPMENTS_REQUEST = 'FETCH_EQUIPMENTS_REQUEST';
export const FETCH_EQUIPMENTS_SUCCESS = 'FETCH_EQUIPMENTS_SUCCESS';
export const FETCH_EQUIPMENTS_FAILURE = 'FETCH_EQUIPMENTS_FAILURE';

export const FETCH_EQUIPMENT_REQUEST = 'FETCH_EQUIPMENT_REQUEST';
export const FETCH_EQUIPMENT_SUCCESS = 'FETCH_EQUIPMENT_SUCCESS';
export const FETCH_EQUIPMENT_FAILURE = 'FETCH_EQUIPMENT_FAILURE';

export const MODIFY_EQUIPMENT_REQUEST = 'MODIFY_EQUIPMENT_REQUEST';
export const MODIFY_EQUIPMENT_SUCCESS = 'MODIFY_EQUIPMENT_SUCCESS';
export const MODIFY_EQUIPMENT_FAILURE = 'MODIFY_EQUIPMENT_FAILURE';

export const MODIFY_EQUIPMENT_RESET = 'MODIFY_EQUIPMENT_RESET';
