server:
  port: 3050
spring:
  datasource:
    password: sa
    url: jdbc:h2:~/accenture-h2/equipment2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
mail:
  password: tttalk0507)%)&
  port: 587
  host: smtp.qiye.163.com
  username: no-reply04@accounts.tttalk.org
online:
  files:
    path: /usr/share/nginx/html/yida-lize-file/images/
    url: http://39.106.104.75:3022/images/
admin:
  password:
    sha256:
      key: equipment
