server:
  port: 3050
spring:
  datasource:
    url: jdbc:h2:~/accenture-h2/equipment;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
  h2:
    console:
      path: /h2-console
      enabled: true
  mail:
    password: 'tttalk0507)%)&'
    port: 587
    host: smtp.qiye.163.com
    username: 'no-reply04@accounts.tttalk.org'
    person: 'no-reply'
    properties:
      mail:
        smtp:
            auth: true
            starttls:
                enable: true
  ldap:
    embedded:
      ldif: 'classpath:test-server.ldif'
      base-dn: 'dc=springframework,dc=org'
      port: 8389
online:
  files:
    path: /tmp/
    url: http://localhost:3022/images/
admin:
  password:
    sha256:
      key: equipment
